theme = "catppuccin_mocha"

[editor]
line-number = "relative"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
git-ignore = true

[editor.lsp]
display-messages = true